#!/bin/bash

#
# Checks if we are running the master PostgreSQL instance by querying pacemaker
#

RESOURCE_NAME=pgInstance:1
CRM_RESOURCE="/usr/sbin/crm_resource"

if [ "$(CRM_RESOURCE -r pgInstance:1 --locate -Q 2>/dev/null)" = "$(uname -n)" ]; then
	exit 0;
else
	exit 1;
fi
